# Resources settings
source:      .
destination:      ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
timezone:    Asia/Hongkong
gems:        []
highlighter:     rouge

# Site settings
email: master@joytou.net.cn
author: Joytou Wu
owner_name: Joytou Wu
git_username: joytou
repo: JOYTOU

#Server
url: https://www.joytou.net
github: https://github.com/joytou/
coding: https://coding.net/joytou/
baseurl: ""

#Page settings
future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
markdown: kramdown

#Pagination setting
paginatenum: 2
 
exclude: ['README.md','Manifest.md']
include: ['robots.txt','404.html','.htaccess']

# Description
description: "只为博客而生，也因为博客而存在。Not only for the existence of the blog, but also because of the existence of the blog."

# Keywords
keywords:
        - "git"
        - "bootstrap"
        - "blog"
        - "joytou"
        - "markdown"
        - "jekyll"
        - "博客"
        - "博客模板"
        - "jekyll主题"
        - "jekyll theme"
        - "liquid"
        - "静态"
        - "响应式"
        - "Coding"
        - "gitee"
        - "github"
        
        
#Update configuration

versioncode: 1
        #The current versioncode.
        
versionname: "1.0.1"
        #The current versionname.
        
#remind: true
        #Whether to remind you to upgrade the latest version when there is the latest version.


#Others

#CNZZ
cnzz:
  id: "1272874117"
  show: "pic"
  HttpsEncryption: false

#ChangYan
changyan:
  appid: "cys9CkC15"
  appconf: "prod_6c14cfe1b9706846e412ddac9bcdb068"

